# Generated by Django 4.0.1 on 2022-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('synopsis', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
